name: "Deploy staging"

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]

jobs:
  depoy-staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
    - name: Deploy
      if: github.ref == 'refs/heads/staging'
      run: curl ${{ secrets.ENVOYER_HOOK }}?sha=${{ github.sha }}
