name: "Deploy staging"

on:
  push:
    branches: [ "staging" ]
  workflow_run:
    workflows: [ "Laravel" ]
    types:
      - completed

jobs:
  depoy-staging:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy staging
      uses: Glennmen/ploi-deploy-action@v1.2.0
      with:
        webhook_url: ${{ secrets.ENVOYER_HOOK_STAGING }}
